name: Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up notebook state cache
              uses: actions/cache@v2
              with:
                path: pluto_state_cache
                key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ hashFiles('**/*.jl') }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1
            - name: Run Pluto notebooks and generate website
              shell: julia --color=yes {0}
              run: |
                cd("newwebsite")
                run(`cp generate.jl generate2.jl`)
                using Pkg
                Pkg.add("Pluto")
                import Pluto
                Pluto.activate_notebook_environment("generate2.jl")
                Pkg.instantiate()
                include("./generate.jl")
                cd("..")
            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: ./website/__site
